version: '3'
volumes:
  dados:
networks: 
  database:
  web:
  queuenetwork:
services :
  db:
    image: postgres:9.6
    volumes:
      #data volumes
      - dados:/var/lib/postgresql/data
      #scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: 
      - database
  frontend:
    image: nginx:1.13
    volumes:
      #site
      - ./web:/usr/share/nginx/html/
      # config reverse proxy
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks: 
      - web
    depends_on:
      - app
  app:
    image: python:3.6
    volumes:
      #application
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    networks: 
      - database 
      - web
      - queuenetwork
    depends_on:
      - db
      - queue
  queue:
    image: redis:3.2
    networks: 
      - queuenetwork
  worker:
    image: python:3.6
    volumes:
      - ./worker:/worker
    working_dir: /worker
    command: bash ./app.sh
    networks:
      - queuenetwork
    depends_on:
      - queue
      





  


